config/routes.rb
Rails.application.routes.draw do

  post '/' => 'contacts#create'

  get 'admin' => 'sessions#new'

  post 'admin' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'users/edit'

  root 'pages#home'

  resources :users

  resources :locations, only: [:edit, :update]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true
  attribute :subject,   :validate => true
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => %(#{subject}),
      :to => User.where(admin: true).map(&:email_support),
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user

	geocoded_by :address
	after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :email, presence: true
	validates :password, presence: true, allow_nil: true
	has_one :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
  	@contact = Contact.new(params[:contact])
  	@contact.request = request
  	if verify_recaptcha(model: @contact) && @contact.deliver
      flash[:success] = "Message has send"
  		redirect_to "/#contact"
  	else
  		flash[:error] = "Cannot send message, please fill require information"
  		redirect_to '/#contact'
  	end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :admin_user, only: [:edit, :update]

  def edit
  	@user = User.find(params[:id])
  	@location = Location.first
  end

  def update
  	@user = User.find(params[:id])
  	@location = Location.find(params[:id])
  	if @location.update(location_params)
  		flash[:success] = "Location edited"
  		render :edit
  	else
  		flash[:error] = "Can't update location"
  	end
  end

  private

  	def location_params
  		params.require(:location).permit(:address, :city, :user_id)
  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@contact = Contact.new
  	@user = User.first
  	@location = Location.first
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password])
  		log_in @user
		  redirect_to root_path
  	else
      flash[:danger] = "Email or Password Invalid"
  		render :new  		
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update]
  before_action :admin_user, only: [:edit, :update]

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:success] = "Updated"
  		render :edit
  	else
      flash[:danger] = "Need Information"
  		render :edit
  	end
  end

  private

  	def set_user
  		@user = User.find(params[:id])
  	end

  	def user_params
  		params.require(:user).permit(:email, :phone, :email_support, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def admin_user
		redirect_to root_path unless current_user.admin?
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spinwashlounge</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="images/png" href="assets/favicon.png" />
</head>
<body>
<!-- Page Loader -->
<section id="pageloader">
  <div class="loader-item fa fa-spin colored-border"></div>
</section>


<div class="container">
	<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>" role="alert"><%= message %></div>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/locations/edit.html.erb
<div class="row">
	<div class="col-md-12 col-md-offset-4">
	<%= simple_form_for(@location, html: {class: "admin_form col-xs-4 animated fadeInLeft visible"} ) do |f| %>
		<h2>Address</h2>
		<%= f.input :address, required: true, placeholder: "Phone", label: false %>
		<%= f.input :city, required: true, placeholder: "City", label: false %>
		<%= f.hidden_field :user_id, required: true, value: @user.id %>
		<div class="divider"></div>
		<%= @location.longitude %>, <%= @location.latitude %>
		<div class="divider"></div>
		<%= f.button :submit, "Update Location", class: "btn btn-primary form-btn" %>
		<div class="divider"></div>
		<%= link_to "Back", '/', class: "btn back-btn" %>
	<% end %>
	</div>
</div>

app/views/pages/_about.html.erb
<!-- About -->

<section id="about" class="container waypoint">
  <div class="inner">
    <!-- Header -->
    <h1 class="header semibold dark">Retina ready professionel and <span class="colored">clean</span> design.</h1>
    <!-- Description -->
    <h4 class="h-desc">On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and by the <span class="colored bold">charms</span> of pleasure of the moment, so blinded by desire, that they cannot foresee the pain </h4>
    <!-- Boxes -->
    <div class="boxes">

      <!-- Box 1 -->
      <div class="col-xs-3 about-box animated" data-animation="fadeIn" data-animation-delay="100">
        <a class="about-icon">
          <i class="fa fa-gear "></i>
        </a>
        <p class="uppercase normal about-head">LAUNDRY, REDEFINED.</p>
        <p class="light about-text">Portland's only eco-friendly laundromat, bar and cafe places state-of-the-art, energy-efficient Electrolux washers and dryers + sustainable laundry products, in a retro-mod cafe/bar environment.</p>
      </div>

      <!-- Box 2 -->
      <div class="col-xs-3 about-box animated" data-animation="fadeIn" data-animation-delay="300">
        <a class="about-icon">
          <i class="fa fa-pagelines"></i>
        </a>
        <p class="uppercase normal about-head">LAUNDRY TASK</p>
        <p class="light about-text">Save time and money, reduce your carbon footprint, and enjoy every minute of Portland's totally redefined laundromat experience. </p>
      </div>

      <!-- Box 3 -->
      <div class="col-xs-3 about-box animated" data-animation="fadeIn" data-animation-delay="500">
        <a class="about-icon">
          <i class="fa fa-star"></i>
        </a>
        <p class="uppercase normal about-head">ADDITIONAL AMENITIES</p>
        <p class="light about-text">Fully attended, always bright and clean. 24-hour surveillance. Pay with credit/debit card, apple pay or coin. Change machine. Free WiFi
         

        </p>
      </div>

      <!-- Box 4 -->
      <div class="col-xs-3 about-box animated" data-animation="fadeIn" data-animation-delay="700">
        <a class="about-icon">
          <i class="fa fa-clock-o"></i>
        </a>
        <p class="uppercase normal about-head">WASH & DRY IN ONLY 45 MINUTES </p>
        <p class="light about-text">Choose multiple washers and dryers, or dump all of your laundry from the past month into one of Spin's largest-capacity machines.</p>
      </div>
    </div><!-- End Boxes -->
  </div><!-- End About Inner -->
</section><!-- End About Section -->

app/views/pages/_contact.html.erb
 <!-- Contact Section -->
  <section id="contact" class="container parallax5">

    <%= render 'google_map' %>
    <!-- Contact Inner -->
    <div class="inner contact">
      <!-- Header -->
      <h1 class="header semibold white">Get In <span class="extrabold">Touch</span></h1>

      <!-- Description -->
      <h4 class="h-desc white contact-text">On the other hand, we denounce with righteous indignation and dislike men who are so beguiled. </h4>
      <!-- Form Area -->
      <div class="contact-form">
       <div class="col-xs-12 animated" data-animation="fadeInLeft" data-animation-delay="300">
         <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>" role="alert"><%= message %></div>
      <% end %>
        </div>
        <!-- Form -->
        <%= simple_form_for @contact, url: root_path do |f| %>
        <!-- Left Inputs -->
        <div class="col-xs-6 animated" data-animation="fadeInLeft" data-animation-delay="300">
          <!-- Name -->
          <%= f.input :name, required: true, placeholder: "Name", label: false, input_html: { class: "form light" } %>
          <!-- Email -->
          <%= f.input :email, required: true, placeholder: "Email", label: false, input_html: { class: "form light" } %>
          <!-- Subject -->
          <%= f.input :subject, required: true, placeholder: "Subject", label: false, input_html: { class: "form light" } %>
        </div><!-- End Left Inputs -->
        <!-- Right Inputs -->
        <div class="col-xs-6 animated" data-animation="fadeInRight" data-animation-delay="300">
          <!-- Message -->
          <%= f.input :message, as: :text, required: true, placeholder: "Message", label: false, input_html: { class: "form textarea light" } %>
          <%= recaptcha_tags %>
        </div><!-- End Right Inputs -->
        <!-- Bottom Submit -->
        <div class="relative fullwidth col-xs-12">
          <!-- Send Button -->
          <%= f.button :submit, "Send Message", class: "form-btn light" %>
        </div><!-- End Bottom Submit -->
          <!-- Clear -->
          <div class="clear"></div>
        <% end %>
        
        <!-- Your Mail Message -->
        <div class="mail-message-area">
          <!-- Message -->
          <div class="alert gray-bg mail-message not-visible-message">
            <strong>Thank You !</strong> Your email has been delivered.
          </div>
        </div>

      </div><!-- End Contact Form Area -->
    </div><!-- End Inner -->
  </section><!-- End Contact Section -->

app/views/pages/_feature.html.erb
<!-- Features -->
	<section id="features" class="container">

		<div class="inner">

			<!-- Header -->
			<h1 class="header light dark">Why do you choose <span class="condiment">Oxygen ?</span></h1>

			<!-- Description -->
			<h4 class="h-desc dark">On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and by the <span class="colored bold">charms</span> of pleasure of the moment, so blinded by desire, that they cannot foresee the pain </h4>

			<div class="features-boxes">

				<!-- Box 1 -->
				<div class="col-xs-4 f-box animated" data-animation="fadeIn" data-animation-delay="1">
					<!-- Icon -->
					<a class="f-icon">
						<i class="fa fa-tablet"></i>
					</a>
					<!-- Header -->
					<p class="feature-head uppercase">100% Responsive Design</p>
					<!-- Text -->
					<p class="feature-text light">On the other hand, we denounce with righteous indignatin men who are so beguiled and by the charms of pleasure of the moment, so blinded by desire,.</p>
				</div>


				<!-- Box 2 -->
				<div class="col-xs-4 f-box animated" data-animation="fadeIn" data-animation-delay="100">
					<!-- Icon -->
					<a class="f-icon">
						<i class="fa fa-html5"></i>
					</a>
					<!-- Header -->
					<p class="feature-head uppercase">html5 & css3</p>
					<!-- Text -->
					<p class="feature-text light">On the other hand, we denounce with righteous indignatin men who are so beguiled and by the charms of pleasure of the moment, so blinded by desire,.</p>
				</div>


				<!-- Box 3 -->
				<div class="col-xs-4 f-box animated" data-animation="fadeIn" data-animation-delay="200">
					<!-- Icon -->
					<a class="f-icon">
						<i class="fa fa-cogs"></i>
					</a>
					<!-- Header -->
					<p class="feature-head uppercase">Clean coding</p>
					<!-- Text -->
					<p class="feature-text light">On the other hand, we denounce with righteous indignatin men who are so beguiled and by the charms of pleasure of the moment, so blinded by desire,.</p>
				</div>


				<!-- Box 4 -->
				<div class="col-xs-4 f-box animated" data-animation="fadeIn" data-animation-delay="300">
					<!-- Icon -->
					<a class="f-icon">
						<i class="fa fa-check"></i>
					</a>
					<!-- Header -->
					<p class="feature-head uppercase">Easy customizable</p>
					<!-- Text -->
					<p class="feature-text light">On the other hand, we denounce with righteous indignatin men who are so beguiled and by the charms of pleasure of the moment, so blinded by desire,.</p>
				</div>


				<!-- Box 5 -->
				<div class="col-xs-4 f-box animated" data-animation="fadeIn" data-animation-delay="400">
					<!-- Icon -->
					<a class="f-icon">
						<i class="fa fa-gear"></i>
					</a>
					<!-- Header -->
					<p class="feature-head uppercase">Retina ready </p>
					<!-- Text -->
					<p class="feature-text light">On the other hand, we denounce with righteous indignatin men who are so beguiled and by the charms of pleasure of the moment, so blinded by desire,.</p>
				</div>


				<!-- Box 6 -->
				<div class="col-xs-4 f-box animated" data-animation="fadeIn" data-animation-delay="500">
					<!-- Icon -->
					<a class="f-icon">
						<i class="fa fa-rocket"></i>
					</a>
					<!-- Header -->
					<p class="feature-head uppercase">7X24 support</p>
					<!-- Text -->
					<p class="feature-text light">On the other hand, we denounce with righteous indignatin men who are so beguiled and by the charms of pleasure of the moment, so blinded by desire,.</p>
				</div>

				<div class="clear"></div>

			</div><!-- End Features Boxes -->

		</div> <!-- End Features Inner -->

	</section><!-- End Features Section -->

app/views/pages/_footer.html.erb
<!-- Footer -->
	<footer class="footer">
		<!-- Your Company Name -->
		<%= image_tag 'logo-icon', class: "footer-logo" %>
		<!-- Copyright -->
		<p class="copyright normal">Copyright © 2016 All Rights Reserved. Spinwashlounge.com</p>
		<p class="white normal">Dev by <a href="yummlabs.com">yummlabs.com</a></p>
	</footer><!-- End Footer -->

app/views/pages/_google_map.html.erb
	<div id="map" class="container close-map">
		<!-- Open/Close Button -->
		<a id="map-button" class="google-map-big-button uppercase bold condensed white scroll close-map-button" href="#map" >where are we ? click for google map <i class="fa fa-caret-down"></i></a>
	
		<!-- Google Map -->
		<div id="google-map"></div>
	</div><!-- End Google Map Section -->
	


 	<script type="text/javascript">

		var map;
		var myCenter = {lat: <%= @location.latitude %>, lng: <%= @location.longitude %>};
		function initMap() {
		  map = new google.maps.Map(document.getElementById('google-map'), {
		    center: myCenter,
		    zoom: 15
		  });
		var marker = new google.maps.Marker({
			position: myCenter,
			map: map,
		});
		}

    </script>
     <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtDGSiW2PEYJ97s3roIFCC0eyCETEgLFU&callback=initMap">
    </script>

app/views/pages/_navigation.html.erb
<!-- Navigation -->
<section id="navigation" class="not-visible-nav white-nav">
  <!-- Navigation Inner -->
  <div class="nav-inner">
    <!-- Site Logo -->
    <div class="site-logo">
      <a href="#home" class="scroll logo">
        <!-- Your Logo -->
        <img src="assets/logo.png" alt="logo" />
      </a>
    </div><!-- End Site Logo -->
    <a class="mini-nav-button dark"><i class="fa fa-bars"></i></a>
    <!-- Navigation Menu -->
    <div class="nav-menu">
      <ul class="nav uppercase condensed bold">
        <li><a href="#home" class="scroll">home</a></li>
        <li><a href="#about" class="scroll">about us</a></li>
        <li><a href="#services" class="scroll">services</a></li>
        <li><a href="#features" class="scroll">features</a></li>
        <li><a href="#contact" class="scroll">contact</a></li>
        <% if current_user && current_user.admin? %>
        <li class="dropdown-toggle nav-toggle"><a href="#" class="scroll">admin<b data-toggle="dropdown" class="caret"></b></a>
            <!-- DropDown Menu -->
            <ul class="dropdown-menu uppercase gray-border" style="display: none;">
              <li><%= link_to "Edit Information", edit_user_path(current_user) %></li>
              <li><%= link_to "Edit Location", edit_location_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul><!-- End DropDown Menu -->
          </li>
          <% end %>
      </ul>
    </div><!-- End Navigation Menu -->
  </div><!-- End Navigation Inner -->
</section><!-- End Navigation Section -->

app/views/pages/_service.html.erb
  <!-- Services -->
  <section id="services" class="container parallax1">
    <div class="inner">

      <!-- Header -->
      <h1 class="header bold white">Our Services</h1>

      <!-- Description -->
      <h4 class="h-desc white">On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and by the <span class="white bold">charms</span> of pleasure of the moment, so blinded by desire, that they cannot foresee the pain </h4>

      <!-- Boxes -->
      <div class="service-boxes">

        <!-- Box 1 -->
        <div class="col-xs-2 service-box animated" data-animation="fadeIn" data-animation-delay="200" data-toggle="tooltip" data-placement="top" title="Electrolux 450 G-force washers and dryers with EcoPower technology are the most energy-efficient machines in the world. Reduce wear and tear, even on your most delicate laundry ">
          <!-- Icon -->
          <a class="service-icon">
            <i class="fa fa-flash"></i>
          </a>
          <!-- Header -->
          <p class="service-header light white">Equipment</p>
        </div>

        <!-- Box 2 -->
        <div class="col-xs-2 service-box animated" data-animation="fadeIn" data-animation-delay="200" data-toggle="tooltip" data-placement="top" title="Doing laundry at Spin is cheaper per pound than any other Portland-area laundromat. Wash cycles may cost a little more than old school top-loading washers, but the high extraction speed of Spin's machines makes up for it. ">
          <!-- Icon -->
          <a class="service-icon">
            <i class="fa fa-bullseye"></i>
          </a>
          <!-- Header -->
          <p class="service-header light white">Spin SAVINGS</p>
        </div>


        <!-- Box 3 -->
        <div class="col-xs-2 service-box animated" data-animation="fadeIn" data-animation-delay="200" data-toggle="tooltip" data-placement="top" title="Oregon's first and only completely hypoallergenic machines - perfect if your sensitive to the harsh chemicals commonly found in commercial laundry products. ">
          <!-- Icon -->
          <a class="service-icon">
            <i class="fa fa-camera"></i>
          </a>
          <!-- Header -->
          <p class="service-header light white">Prontos</p>
        </div>


        <!-- Box 4 -->
        <div class="col-xs-2 service-box animated" data-animation="fadeIn" data-animation-delay="200" data-toggle="tooltip" data-placement="top" title="Credit + Debit – There's a card reader attached to every Spin washer and dryer. 

Smartphone - Use Apple Pay on your iPhone 6, or download Google Wallet on your Android Phone.

Coin op – Old school style - we've even got a change machine.">
          <!-- Icon -->
          <a class="service-icon">
            <i class="fa fa-twitter"></i>
          </a>
          <!-- Header -->
          <p class="service-header light white">Ways to PAY</p>
        </div>


        <!-- Box 5 -->
        <div class="col-xs-2 service-box animated" data-animation="fadeIn" data-animation-delay="200" data-toggle="tooltip" data-placement="top" title="Spin sells only environmentally friendly soaps, bleaches and stain removers - free of harsh chemicals and fragrances commonly found in commercial laundry products. Choses from our line of Nellie's All Natural, Charlie's Soap, or The Laundress. ">
          <!-- Icon -->
          <a class="service-icon">
            <i class="fa fa-globe"></i>
          </a>
          <!-- Header -->
          <p class="service-header light white">ECO-FRIENDLY SOAP

</p>
        </div>


        <!-- Box 6 -->
        <div class="col-xs-2 service-box animated" data-animation="fadeIn" data-animation-delay="200" data-toggle="tooltip" data-placement="top" title="There are many variations of passages of Lorem Ipsum available. ">
          <!-- Icon -->
          <a class="service-icon">
            <i class="fa fa-desktop"></i>
          </a>
          <!-- Header -->
          <p class="service-header light white">Web Design</p>
        </div>

        <div class="clear"></div>

      </div> <!-- End Boxes -->

    </div><!-- End Service Inner -->
  </section><!-- End Services Section -->

app/views/pages/_social_and_address.html.erb
<section id="site-socials" class="no-padding white-bg">
		<div class="site-socials inner no-padding">
			<!-- Socials -->
			<div class="socials">
				<!-- Facebook -->
				<a href="#" target="_blank" class="social">
					<i class="fa fa-facebook"></i>
				</a>
				<!-- Twitter -->
				<a href="#" target="_blank" class="social">
					<i class="fa fa-twitter"></i>
				</a>
				<!-- Google Plus -->
				<a href="#" target="_blank" class="social">
					<i class="fa fa-google-plus"></i>
				</a>
				<!-- Linkedin -->
				<a href="#" target="_blank" class="social">
					<i class="fa fa-linkedin"></i>
				</a>
				<!-- Instagram -->
				<a href="#" class="social">
					<i class="fa fa-instagram"></i>
				</a>
				<!-- Vimeo -->
				<a href="#" target="_blank" class="social">
					<i class="fa fa-vimeo-square"></i>
				</a>
			</div>
			<!-- Adress, Mail -->
			<div class="address">
				<!-- Phone Number, Mail -->
				<p>(021) - <%= @user.phone %> & <a href="mailto:<%= @user.email_support %>" class="bold dark"><%= @user.email_support %></a></p>
				<!-- Adress -->
				<p><%= @location.address %>, <span class="bold colored"><%= @location.city %></span></p>
				<!-- Top Button -->
				<a href="#home" class="scroll top-button">
					<i class="fa fa-angle-double-up"></i>
				</a>
			</div><!-- End Adress, Mail -->
		</div><!-- End Inner -->
	</section><!-- End Site Socials and Address -->

app/views/pages/home.html.erb
<%= render 'navigation' %>
<!-- Home Section -->
<section id="home">   
<div id="slides" class="home parallax pattern-black">
  <div class="home-details">
    <!-- Your Logo -->
    <div class="logo">                                                      
      <img src="assets/logo-icon.png" alt="Logo" />
    </div>
    <div class="hometexts">
        <!-- Slide Texts -->
        <ul class="slide-text condensed">
          <li class="hometext bold uppercase">Welcome to <span class="colored"> oxygen</span></li>
          <li class="hometext bold uppercase">We Love to <span class="colored"> Design</span></li>
          <li class="hometext bold uppercase">We Are <span class="colored"> Creative</span></li>
        </ul>
    </div>
    <!-- Fixed Text -->
    <h1 class="fixed-text uppercase bold condensed">the goods you need now !</h1>
    <!-- Home Categories -->
    <ul class="home-categories">
      <li class="h-item uppercase ">web design</li>
      <li class="h-item uppercase ">one page</li>
      <li class="h-item uppercase ">analystic</li>
      <li class="h-item uppercase ">photography</li>
      <li class="h-item uppercase ">cool animations</li>
    </ul>
    <!-- Bottom Arrow -->
    <a href="#about" class="home-arrow scroll uppercase bold">
      <img src="assets/bottom-arrow.png" alt="bottom" />
      <span>what we do ?</span>
    </a>
  </div><!-- End Home Texts -->
</div><!-- End Home Details -->
</section><!-- End Home Section -->

<%= render 'about' %>
<%= render 'service' %>
<%= render 'feature' %>
<%= render 'contact' %>
<%= render 'social_and_address' %>
<%= render 'footer' %>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-12 col-md-offset-4">
	<%= simple_form_for(@user, html: {class: "admin_form col-xs-4 animated fadeInLeft visible"} ) do |f| %>
		<h2>Information</h2>
		<%= f.input :phone, required: true, placeholder: "Phone", label: false %>
		<%= f.input :email_support, required: true, placeholder: "Email Support", label: false %>
		<div class="divider"></div>
		<%= f.input :email, required: true, placeholder: "Email", label: false %>
		<%= f.input :password, required: true, placeholder: "Password", label: false %>
		<%= f.input :password_confirmation, required: true, placeholder: "Password Confirmation", label: false %>

		<%= f.button :submit, "Update Information", class: "btn btn-primary form-btn" %>
		<div class="divider"></div>
		<%= link_to "Back", '/', class: "btn back-btn" %>
	<% end %>
	</div>
</div>